title: Diana Danilenko
description: I am a PhD candidate at the Potsdam Institute for Climate Impact Research. My research topics include: evidence synthesis methods, empiritcal ex-post policy evaluation, intersectional inequality in the context of climate change adaptation and adaptation, NLP and Big Data. 
theme: jekyll-theme-minimal
